name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Make sure the repository is checked out

      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}  # Ensure the remote host IP or domain is stored in secrets
          username: ${{ secrets.USERNAME }}  # SSH username
          key: ${{ secrets.KEY }}  # SSH private key stored in secrets
          port: 22  # Optional: specify the SSH port (default is 22)
          script: |
            sudo su
            rm -rf anonymization-api
            git clone git@github.com:ahmedbesbes/anonymization-api.git
            cd anonymization-api
            sudo docker-compose down
            sudo docker-compose -f docker-compose.prod.yaml up --build -d
